In [ ]:
# Write a function that takes start and end of a range returns a Pandas series object containing numbers within that range.
# In case the user does not pass start or end or both they should default to 1 and 10 respectively. eg.
# range_series() -> Should Return a pandas series from 1 to 10
# range_series(5) -> Should Return a pandas series from 5 to 10
# range_series(5, 10) -> Should Return a pandas series from 5 to 15Create a method that takes n
# numpy arrays of same dimensions sums them and return the answer.

In [5]:
import pandas as pd
import numpy as np
ser=[]

In [6]:
def range_series(a=1,b=10):
    for i in range(a,(b+1),1):
        ser.append(i)
    ser1=pd.Series(ser)
    print(ser1)

In [9]:
range_series(1,10)

0      7
1      8
2      9
3     10
4     11
5     12
6     13
7     14
8      1
9      2
10     3
11     4
12     5
13     6
14     7
15     8
16     9
17    10
dtype: int64

In [10]:
range_series(5)

0      7
1      8
2      9
3     10
4     11
5     12
6     13
7     14
8      1
9      2
10     3
11     4
12     5
13     6
14     7
15     8
16     9
17    10
18     5
19     6
20     7
21     8
22     9
23    10
dtype: int64

In [11]:
range_series(5,10)

0      7
1      8
2      9
3     10
4     11
5     12
6     13
7     14
8      1
9      2
10     3
11     4
12     5
13     6
14     7
15     8
16     9
17    10
18     5
19     6
20     7
21     8
22     9
23    10
24     5
25     6
26     7
27     8
28     9
29    10
dtype: int64

In [ ]:
# 2) Create a function that takes in two lists named keys and values as arguments.Keys would be strings and contain n string 
# values. Values would be a list containing n lists. The methods should return a new pandas dataframe with keys as column names 
# and values as their corresponding values
# e.g. -> create_dataframe(["One", "Two"], [["X", "Y"], ["A", "B"]]) -> should return a dataframe
# One Two
# 0 X A
# 1 Y B

In [12]:
keys=[]
values=[]

In [13]:
def Dataframe(keys,values):
    global df
    df=pd.DataFrame(values)
    df.columns=keys
    print(df)
    return pd.DataFrame(df)

In [14]:
df1=Dataframe(["A","B","C"],[["x","y","z"],[10,20,30]])

    A   B   C
0   x   y   z
1  10  20  30

In [15]:
df2=Dataframe(["A","B","C"],[["i","j","k"],[40,50,60]])

    A   B   C
0   i   j   k
1  40  50  60

In [ ]:
# 3) Create a function that concatenates two dataframes. Use previously created function to create two dataframes and pass them 
# as parameters Make sure that the indexes are reset before returning:

In [16]:
def concatenateDF(df1,df2):
    frame=pd.concat([df1,df2],ignore_index=True)
    return frame

In [17]:
concatenateDF(df1,df2)

    A   B   C
0   x   y   z
1  10  20  30
2   i   j   k
3  40  50  60

In [ ]:
# 4) Write code to load data from cars.csv into a dataframe and print its details. Details like: 'count', 'mean', 'std', 'min',
# '25%', '50%', '75%', 'max'.

In [21]:
cars=pd.read_csv("C:\Seema Python CSV\cars.csv")
cars.describe()

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

In [ ]:
# 5) Write a method that will take a column name as argument and return the name of the column with which the given column has 
# the highest correlation. The data to be used is the cars dataset. The returned value should not the column named that was 
# passed as the parameters.
#E.G: get_max_correlated_column('mpg') -> should return 'compression-ratio'

In [22]:
c=cars.corr()
c

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
symboling,1.000000,-0.531954,-0.357612,-0.232919,-0.541038,-0.227691,-0.105790,-0.178515,-0.035823,0.034606
wheel-base,-0.531954,1.000000,0.874587,0.795144,0.589435,0.776386,0.569329,0.249786,-0.470414,-0.544082
length,-0.357612,0.874587,1.000000,0.841118,0.491029,0.877728,0.683360,0.158414,-0.670909,-0.704662
width,-0.232919,0.795144,0.841118,1.000000,0.279210,0.867032,0.735433,0.181129,-0.642704,-0.677218
height,-0.541038,0.589435,0.491029,0.279210,1.000000,0.295572,0.067149,0.261214,-0.048640,-0.107358
curb-weight,-0.227691,0.776386,0.877728,0.867032,0.295572,1.000000,0.850594,0.151362,-0.757414,-0.797465
engine-size,-0.105790,0.569329,0.683360,0.735433,0.067149,0.850594,1.000000,0.028971,-0.653658,-0.677470
compression-ratio,-0.178515,0.249786,0.158414,0.181129,0.261214,0.151362,0.028971,1.000000,0.324701,0.265201
city-mpg,-0.035823,-0.470414,-0.670909,-0.642704,-0.048640,-0.757414,-0.653658,0.324701,1.000000,0.971337
highway-mpg,0.034606,-0.544082,-0.704662,-0.677218,-0.107358,-0.797465,-0.677470,0.265201,0.971337,1.000000

In [23]:
import numpy as np
np.fill_diagonal(c.values,-3)
c

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
symboling,-3.000000,-0.531954,-0.357612,-0.232919,-0.541038,-0.227691,-0.105790,-0.178515,-0.035823,0.034606
wheel-base,-0.531954,-3.000000,0.874587,0.795144,0.589435,0.776386,0.569329,0.249786,-0.470414,-0.544082
length,-0.357612,0.874587,-3.000000,0.841118,0.491029,0.877728,0.683360,0.158414,-0.670909,-0.704662
width,-0.232919,0.795144,0.841118,-3.000000,0.279210,0.867032,0.735433,0.181129,-0.642704,-0.677218
height,-0.541038,0.589435,0.491029,0.279210,-3.000000,0.295572,0.067149,0.261214,-0.048640,-0.107358
curb-weight,-0.227691,0.776386,0.877728,0.867032,0.295572,-3.000000,0.850594,0.151362,-0.757414,-0.797465
engine-size,-0.105790,0.569329,0.683360,0.735433,0.067149,0.850594,-3.000000,0.028971,-0.653658,-0.677470
compression-ratio,-0.178515,0.249786,0.158414,0.181129,0.261214,0.151362,0.028971,-3.000000,0.324701,0.265201
city-mpg,-0.035823,-0.470414,-0.670909,-0.642704,-0.048640,-0.757414,-0.653658,0.324701,-3.000000,0.971337
highway-mpg,0.034606,-0.544082,-0.704662,-0.677218,-0.107358,-0.797465,-0.677470,0.265201,0.971337,-3.000000

In [24]:
def getcolumn (df,column):
    a=df[column].max()
    return c[column].sort_values(ascending=False).index[1]

In [28]:
getcolumn(c,'highway-mpg')

'compression-ratio'